import React from "react";

export const Health = [
  { value: "hypertension", label: "Hypertension" },
  { value: "heart-disease", label: "Heart Disease" },
  { value: "arrhythmia", label: "Arrhythmia" },
  { value: "atherosclerosis", label: "Atherosclerosis" },
  { value: "congestive-heart-failure", label: "Congestive Heart Failure" },
  { value: "asthma", label: "Asthma" },
  {
    value: "chronic-obstructive-pulmonary-disease",
    label: "Chronic Obstructive Pulmonary Disease (COPD)",
  },
  { value: "pulmonary-hypertension", label: "Pulmonary Hypertension" },
  { value: "bronchitis", label: "Bronchitis" },
  { value: "arthritis", label: "Arthritis" },
  { value: "osteoporosis", label: "Osteoporosis" },
  { value: "lower-back-pain", label: "Lower Back Pain" },
  { value: "tendinitis", label: "Tendinitis" },
  { value: "scoliosis", label: "Scoliosis" },
  { value: "diabetes-type-1", label: "Diabetes Type 1" },
  { value: "diabetes-type-2", label: "Diabetes Type 2" },
  { value: "obesity", label: "Obesity" },
  { value: "metabolic-syndrome", label: "Metabolic Syndrome" },
  { value: "hypothyroidism", label: "Hypothyroidism" },
  { value: "hyperthyroidism", label: "Hyperthyroidism" },
  { value: "parkinsons-disease", label: "Parkinson's Disease" },
  { value: "multiple-sclerosis", label: "Multiple Sclerosis" },
  { value: "epilepsy", label: "Epilepsy" },
  { value: "stroke", label: "Stroke" },
  { value: "migraine", label: "Migraine" },
  { value: "depression", label: "Depression" },
  { value: "anxiety-disorders", label: "Anxiety Disorders" },
  { value: "eating-disorders", label: "Eating Disorders" },
  { value: "bipolar-disorder", label: "Bipolar Disorder" },
  { value: "rheumatoid-arthritis", label: "Rheumatoid Arthritis" },
  { value: "lupus", label: "Lupus" },
  { value: "hiv-aids", label: "HIV/AIDS" },
  { value: "pregnancy", label: "Pregnancy" },
  { value: "cancer", label: "Cancer" },
  { value: "chronic-pain", label: "Chronic Pain" },
  {
    value: "chronic-fatigue-syndrome",
    label: "Chronic Fatigue Syndrome",
  },
  {value:"None",
label:"None",}
];
